# Generated by Django 3.0.11 on 2020-11-22 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MongoDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_user', models.CharField(max_length=256)),
                ('db_password', models.CharField(max_length=256)),
                ('db_name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='0.0.0.0', max_length=128)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='mongodb.MongoDB')),
            ],
        ),
    ]
